export const SET_CHLOYA_TING_DATA = "workout.SET_CHLOYA_TING_DATA";
export const SET_CHLOYA_TING_PROGRAMS = "workout.SET_CHLOYA_TING_PROGRAMS";
export const CREATE_OWN_PROGRAM = "workout.CREATE_OWN_PROGRAM";
export const EDITING_OWN_PROGRAM = "workout.EDITING_OWN_PROGRAM";
